# Form implementation generated from reading ui file 'frm_customer.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_frm_customer(object):
    def setupUi(self, frm_customer):
        frm_customer.setObjectName("frm_customer")
        frm_customer.resize(1800, 1400)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=frm_customer)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 1781, 1301))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tbl_customer_list = QtWidgets.QTableView(parent=self.verticalLayoutWidget)
        self.tbl_customer_list.setObjectName("tbl_customer_list")
        self.verticalLayout.addWidget(self.tbl_customer_list)

        self.retranslateUi(frm_customer)
        QtCore.QMetaObject.connectSlotsByName(frm_customer)

    def retranslateUi(self, frm_customer):
        _translate = QtCore.QCoreApplication.translate
        frm_customer.setWindowTitle(_translate("frm_customer", "Kunden"))
