# Form implementation generated from reading ui file 'frm_main.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_frm_main(object):
    def setupUi(self, frm_main):
        frm_main.setObjectName("frm_main")
        frm_main.resize(1200, 200)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(frm_main.sizePolicy().hasHeightForWidth())
        frm_main.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(parent=frm_main)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 141, 16))
        self.label_2.setObjectName("label_2")
        frm_main.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=frm_main)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 23))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.menubar.setFont(font)
        self.menubar.setNativeMenuBar(False)
        self.menubar.setObjectName("menubar")
        self.menuDatei = QtWidgets.QMenu(parent=self.menubar)
        self.menuDatei.setObjectName("menuDatei")
        self.menuArtikel = QtWidgets.QMenu(parent=self.menubar)
        self.menuArtikel.setObjectName("menuArtikel")
        self.menuAuftr_ge = QtWidgets.QMenu(parent=self.menubar)
        self.menuAuftr_ge.setObjectName("menuAuftr_ge")
        self.menuKunde = QtWidgets.QMenu(parent=self.menubar)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.menuKunde.setFont(font)
        self.menuKunde.setObjectName("menuKunde")
        frm_main.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=frm_main)
        self.statusbar.setObjectName("statusbar")
        frm_main.setStatusBar(self.statusbar)
        self.actionClose = QtGui.QAction(parent=frm_main)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.actionClose.setFont(font)
        self.actionClose.setObjectName("actionClose")
        self.actionArticle_List = QtGui.QAction(parent=frm_main)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.actionArticle_List.setFont(font)
        self.actionArticle_List.setObjectName("actionArticle_List")
        self.actionOrder_List = QtGui.QAction(parent=frm_main)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.actionOrder_List.setFont(font)
        self.actionOrder_List.setObjectName("actionOrder_List")
        self.actionCustomer_List = QtGui.QAction(parent=frm_main)
        self.actionCustomer_List.setObjectName("actionCustomer_List")
        self.menuDatei.addAction(self.actionClose)
        self.menuArtikel.addAction(self.actionArticle_List)
        self.menuAuftr_ge.addAction(self.actionOrder_List)
        self.menuKunde.addAction(self.actionCustomer_List)
        self.menubar.addAction(self.menuDatei.menuAction())
        self.menubar.addAction(self.menuArtikel.menuAction())
        self.menubar.addAction(self.menuAuftr_ge.menuAction())
        self.menubar.addAction(self.menuKunde.menuAction())

        self.retranslateUi(frm_main)
        QtCore.QMetaObject.connectSlotsByName(frm_main)

    def retranslateUi(self, frm_main):
        _translate = QtCore.QCoreApplication.translate
        frm_main.setWindowTitle(_translate("frm_main", "MainWindow"))
        self.label_2.setText(_translate("frm_main", "created by"))
        self.menuDatei.setTitle(_translate("frm_main", "Datei"))
        self.menuArtikel.setTitle(_translate("frm_main", "Artikel"))
        self.menuAuftr_ge.setTitle(_translate("frm_main", "Aufträge"))
        self.menuKunde.setTitle(_translate("frm_main", "Kunden"))
        self.actionClose.setText(_translate("frm_main", "Beenden"))
        self.actionArticle_List.setText(_translate("frm_main", "Artikel Liste"))
        self.actionOrder_List.setText(_translate("frm_main", "Aufträge Liste"))
        self.actionCustomer_List.setText(_translate("frm_main", "Kunden Liste"))
