# Form implementation generated from reading ui file 'frm_main.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class UiFrmMain(object):
    def setupUi(self, frm_main):
        frm_main.setObjectName("frm_main")
        frm_main.resize(1200, 200)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(frm_main.sizePolicy().hasHeightForWidth())
        frm_main.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(parent=frm_main)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 141, 16))
        self.label_2.setObjectName("label_2")
        frm_main.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=frm_main)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 23))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.menubar.setFont(font)
        self.menubar.setNativeMenuBar(False)
        self.menubar.setObjectName("menubar")
        self.menuDatei = QtWidgets.QMenu(parent=self.menubar)
        self.menuDatei.setObjectName("menuDatei")
        self.menuArtikel = QtWidgets.QMenu(parent=self.menubar)
        self.menuArtikel.setObjectName("menuArtikel")
        self.menuAuftr_ge = QtWidgets.QMenu(parent=self.menubar)
        self.menuAuftr_ge.setObjectName("menuAuftr_ge")
        frm_main.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=frm_main)
        self.statusbar.setObjectName("statusbar")
        frm_main.setStatusBar(self.statusbar)
        self.actionBeenden = QtGui.QAction(parent=frm_main)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.actionBeenden.setFont(font)
        self.actionBeenden.setObjectName("actionBeenden")
        self.actionArtikel_Liste = QtGui.QAction(parent=frm_main)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.actionArtikel_Liste.setFont(font)
        self.actionArtikel_Liste.setObjectName("actionArtikel_Liste")
        self.actionAuftr_ge_Liste = QtGui.QAction(parent=frm_main)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.actionAuftr_ge_Liste.setFont(font)
        self.actionAuftr_ge_Liste.setObjectName("actionAuftr_ge_Liste")
        self.menuDatei.addAction(self.actionBeenden)
        self.menuArtikel.addAction(self.actionArtikel_Liste)
        self.menuAuftr_ge.addAction(self.actionAuftr_ge_Liste)
        self.menubar.addAction(self.menuDatei.menuAction())
        self.menubar.addAction(self.menuArtikel.menuAction())
        self.menubar.addAction(self.menuAuftr_ge.menuAction())

        self.retranslateUi(frm_main)
        QtCore.QMetaObject.connectSlotsByName(frm_main)

    def retranslateUi(self, frm_main):
        _translate = QtCore.QCoreApplication.translate
        frm_main.setWindowTitle(_translate("frm_main", "MainWindow"))
        self.label_2.setText(_translate("frm_main", "created by"))
        self.menuDatei.setTitle(_translate("frm_main", "Datei"))
        self.menuArtikel.setTitle(_translate("frm_main", "Artikel"))
        self.menuAuftr_ge.setTitle(_translate("frm_main", "Aufträge"))
        self.actionBeenden.setText(_translate("frm_main", "Beenden"))
        self.actionArtikel_Liste.setText(_translate("frm_main", "Artikel Liste"))
        self.actionAuftr_ge_Liste.setText(_translate("frm_main", "Aufträge Liste"))
